### PR TITLE
API Controller/Models Features

### PR DESCRIPTION
**Pull request by ucecuzzo2**
Added Features to Controller and Models: Matches, Challenges, and Ladders.

### CODE REVIEW

**Review by matthewgomogda — APPROVED** [review]
looks good

**Review by matthewgomogda — APPROVED** [review]
nice

**Review by dongjin-00 — APPROVED** [review]
good

**Review by dongjin-00 — APPROVED** [review]
good

**Review by ddj1226 — APPROVED** [review]

**Pull request merged**
